image: openjdk:11

cache:
  key: "$CI_JOB_NAME"
  paths:
    - .m2/repository

deploy-rcp-compiler:
  stage: deploy
  script:
    - 'sh src/build-gradle.sh'
    - 'sh src/build-maven-rcp.sh'
    # - 'sh src/build-node-vscode.sh'
  artifacts:
    paths:
    - src/build/
    expire_in: 1 week