image: openjdk:11

cache:
  key: "$CI_JOB_NAME"
  paths:
    - .m2/repository

gradle-compiler-ide:
  stage: deploy
  script:
    - 'sh src/build-gradle.sh'
  artifacts:
    paths:
    - src/build/
    expire_in: 1 week

maven-rcp:
  stage: deploy
  script:
    - 'sh src/build-maven-rcp.sh'
  artifacts:
    paths:
    - src/build/
    expire_in: 1 week